In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data_train=pd.read_csv("/Users/alok.g.v/Desktop/python practice/Guvi Task/Task7/Assignment10_data/trainKNN.txt",sep=',',header=None,
                       names=['id number','refractive index','Na: Sodium','Mg: Magnesium','Al: Aluminum','Si: Silicon',' K: Potassium',
                             'Ca: Calcium','Ba: Barium','Fe: Iron','Type of glass'],index_col=0)
data_train

,refractive index,Na: Sodium,Mg: Magnesium,Al: Aluminum,Si: Silicon,K: Potassium,Ca: Calcium,Ba: Barium,Fe: Iron,Type of glass
id number,,,,,,,,,,
1,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,1
2,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,1
3,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,1
4,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,1
5,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,1
...,...,...,...,...,...,...,...,...,...,...
207,1.51645,14.94,0.00,1.87,73.11,0.00,8.67,1.38,0.0,7
208,1.51831,14.39,0.00,1.82,72.86,1.41,6.47,2.88,0.0,7
209,1.51640,14.37,0.00,2.74,72.85,0.00,9.45,0.54,0.0,7
210,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,7
211,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,7

In [3]:
x=['refractive index','Na: Sodium','Mg: Magnesium','Al: Aluminum','Si: Silicon',' K: Potassium',
                             'Ca: Calcium','Ba: Barium','Fe: Iron']
y=['Type of glass']

In [4]:
X=data_train[x]
y=data_train[y]

In [5]:
scaler=StandardScaler()
X=scaler.fit_transform(X)
print(X,y)

[[ 0.89081203  0.3389847   1.24616006 ... -0.11334995 -0.33935667
  -0.5834224 ]
 [-0.22479561  0.65902807  0.60544985 ... -0.76221546 -0.33935667
  -0.5834224 ]
 [-0.69400706  0.19816562  0.56945489 ... -0.79747989 -0.33935667
  -0.5834224 ]
 ...
 [-0.62182068  1.27351132 -1.98618697 ...  0.38035207  0.77644048
  -0.5834224 ]
 [-0.67760106  0.97907143 -1.98618697 ...  0.18992414  1.8509118
  -0.5834224 ]
 [-0.47416673  1.97760672 -1.98618697 ... -0.36020096  2.94604604
  -0.5834224 ]]            Type of glass
id number
1                      1
2                      1
3                      1
4                      1
5                      1
...                  ...
207                    7
208                    7
209                    7
210                    7
211                    7

[196 rows x 1 columns]

In [6]:
data_test=pd.read_csv('/Users/alok.g.v/Desktop/python practice/Guvi Task/Task7/Assignment10_data/testKNN.txt',header=None,names=['id number','refractive index','Na: Sodium','Mg: Magnesium','Al: Aluminum','Si: Silicon',' K: Potassium',
                             'Ca: Calcium','Ba: Barium','Fe: Iron','Type of glass'],index_col=0)
data_test

,refractive index,Na: Sodium,Mg: Magnesium,Al: Aluminum,Si: Silicon,K: Potassium,Ca: Calcium,Ba: Barium,Fe: Iron,Type of glass
id number,,,,,,,,,,
68,1.52152,13.05,3.65,0.87,72.32,0.19,9.85,0.00,0.17,1
69,1.52152,13.12,3.58,0.90,72.20,0.23,9.82,0.00,0.16,1
70,1.52300,13.31,3.58,0.82,71.99,0.12,10.17,0.00,0.03,1
144,1.51709,13.00,3.47,1.79,72.72,0.66,8.18,0.00,0.00,2
145,1.51660,12.99,3.18,1.23,72.97,0.58,8.81,0.00,0.24,2
146,1.51839,12.85,3.67,1.24,72.57,0.62,8.68,0.00,0.35,2
161,1.51832,13.33,3.34,1.54,72.14,0.56,8.99,0.00,0.00,3
162,1.51934,13.64,3.54,0.75,72.65,0.16,8.89,0.15,0.24,3
163,1.52211,14.19,3.78,0.91,71.36,0.23,9.14,0.00,0.37,3
174,1.52043,13.38,0.00,1.40,72.25,0.33,12.50,0.00,0.00,5
175,1.52058,12.85,1.61,2.17,72.18,0.76,9.70,0.24,0.51,5
176,1.52119,12.97,0.33,1.51,73.39,0.13,11.27,0.00,0.28,5
183,1.51916,14.15,0.00,2.09,72.74,0.00,10.88,0.00,0.00,6
184,1.51969,14.56,0.00,0.56,73.48,0.00,11.22,0.00,0.00,6
185,1.51115,17.38,0.00,0.34,75.41,0.00,6.65,0.00,0.00,6
212,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.00,7
213,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.00,7
214,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.00,7

In [7]:
X_test=data_test[x]
y_test=data_test['Type of glass']
print(X_test,y_test)

           refractive index  Na: Sodium  Mg: Magnesium  Al: Aluminum  \
id number
68                  1.52152       13.05           3.65          0.87
69                  1.52152       13.12           3.58          0.90
70                  1.52300       13.31           3.58          0.82
144                 1.51709       13.00           3.47          1.79
145                 1.51660       12.99           3.18          1.23
146                 1.51839       12.85           3.67          1.24
161                 1.51832       13.33           3.34          1.54
162                 1.51934       13.64           3.54          0.75
163                 1.52211       14.19           3.78          0.91
174                 1.52043       13.38           0.00          1.40
175                 1.52058       12.85           1.61          2.17
176                 1.52119       12.97           0.33          1.51
183                 1.51916       14.15           0.00          2.09
184                 1.51969       14.56           0.00          0.56
185                 1.51115       17.38           0.00          0.34
212                 1.52065       14.36           0.00          2.02
213                 1.51651       14.38           0.00          1.94
214                 1.51711       14.23           0.00          2.08

           Si: Silicon   K: Potassium  Ca: Calcium  Ba: Barium  Fe: Iron
id number
68               72.32           0.19         9.85        0.00      0.17
69               72.20           0.23         9.82        0.00      0.16
70               71.99           0.12        10.17        0.00      0.03
144              72.72           0.66         8.18        0.00      0.00
145              72.97           0.58         8.81        0.00      0.24
146              72.57           0.62         8.68        0.00      0.35
161              72.14           0.56         8.99        0.00      0.00
162              72.65           0.16         8.89        0.15      0.24
163              71.36           0.23         9.14        0.00      0.37
174              72.25           0.33        12.50        0.00      0.00
175              72.18           0.76         9.70        0.24      0.51
176              73.39           0.13        11.27        0.00      0.28
183              72.74           0.00        10.88        0.00      0.00
184              73.48           0.00        11.22        0.00      0.00
185              75.41           0.00         6.65        0.00      0.00
212              73.42           0.00         8.44        1.64      0.00
213              73.61           0.00         8.48        1.57      0.00
214              73.36           0.00         8.62        1.67      0.00   id number
68     1
69     1
70     1
144    2
145    2
146    2
161    3
162    3
163    3
174    5
175    5
176    5
183    6
184    6
185    6
212    7
213    7
214    7
Name: Type of glass, dtype: int64

In [8]:
X_test=scaler.fit_transform(X_test)
X_test

array([[ 0.88089538, -0.67745268,  1.04449191, -0.83588893, -0.57678658,
        -0.24795484,  0.29029673, -0.48794184,  0.24628886],
       [ 0.88089538, -0.61097368,  1.00332645, -0.7827854 , -0.71521535,
        -0.09271355,  0.26793435, -0.48794184,  0.18384943],
       [ 1.4266408 , -0.43053068,  1.00332645, -0.92439482, -0.95746572,
        -0.5196271 ,  0.5288287 , -0.48794184, -0.62786315],
       [-0.7526534 , -0.72493768,  0.93863786,  0.79261939, -0.11535732,
         1.57613032, -0.95454202, -0.48794184, -0.81518144],
       [-0.93333938, -0.73443468,  0.76809524, -0.19864655,  0.17303597,
         1.26564774, -0.48493219, -0.48794184,  0.68336487],
       [-0.27328243, -0.86739269,  1.05625347, -0.18094537, -0.28839329,
         1.42088903, -0.58183581, -0.48794184,  1.3701986 ],
       [-0.29909471, -0.41153668,  0.86218772,  0.35008995, -0.78442974,
         1.1880271 , -0.35075796, -0.48794184, -0.81518144],
       [ 0.07702713, -0.11712967,  0.97980332, -1.04830306, -0.19610744,
        -0.36438581, -0.4252992 , -0.23795266,  0.68336487],
       [ 1.09845605,  0.40520534,  1.12094205, -0.76508423, -1.6842168 ,
        -0.09271355, -0.23894609, -0.48794184,  1.49507746],
       [ 0.47896125, -0.36405167, -1.10199287,  0.10227347, -0.6575367 ,
         0.29538968,  2.26563965, -0.48794184, -0.81518144],
       [ 0.53427329, -0.86739269, -0.15518726,  1.46526413, -0.73828682,
         1.96423355,  0.17848486, -0.08795915,  2.36922947],
       [ 0.7592089 , -0.75342868, -0.90792712,  0.29698642,  0.6575367 ,
        -0.48081677,  1.34878237, -0.48794184,  0.93312259],
       [ 0.01065269,  0.36721734, -1.10199287,  1.32365471, -0.09228585,
        -0.98535097,  1.05807152, -0.48794184, -0.81518144],
       [ 0.20608855,  0.75659435, -1.10199287, -1.38462544,  0.76135828,
        -0.98535097,  1.31151175, -0.48794184, -0.81518144],
       [-2.94301   ,  3.43474841, -1.10199287, -1.77405134,  2.98775446,
        -0.98535097, -2.09502303, -0.48794184, -0.81518144],
       [ 0.56008557,  0.56665435, -1.10199287,  1.19974647,  0.69214389,
        -0.98535097, -0.76073479,  2.24527316, -0.81518144],
       [-0.9665266 ,  0.58564835, -1.10199287,  1.05813705,  0.91132279,
        -0.98535097, -0.73091829,  2.12861155, -0.81518144],
       [-0.74527846,  0.44319334, -1.10199287,  1.30595354,  0.6229295 ,
        -0.98535097, -0.62656055,  2.295271  , -0.81518144]])

In [10]:
def knn_e(k):
    knc_e=KNeighborsClassifier(n_neighbors=k,metric='euclidean')
    knc_e.fit(X,y)
    y_pred=knc_e.predict(X_test)
    acc=accuracy_score(y_test,y_pred)
    print(f'Number of Neighbors : {k}  accuracy : {acc}')

In [11]:
for x in range(1,11,2):
    knn_e(x)

Number of Neighbors : 1  accuracy : 0.6666666666666666
Number of Neighbors : 3  accuracy : 0.6666666666666666
Number of Neighbors : 5  accuracy : 0.6111111111111112
Number of Neighbors : 7  accuracy : 0.6111111111111112
Number of Neighbors : 9  accuracy : 0.6111111111111112

/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [12]:
def knn_m(k):
    knc_m=KNeighborsClassifier(n_neighbors=k,metric='manhattan')
    knc_m.fit(X,y)
    y_pred=knc_m.predict(X_test)
    acc=accuracy_score(y_test,y_pred)
    print(f'Number of Neighbors : {k}  accuracy : {acc}')

In [13]:
for x in range(1,11,2):
    knn_m(x)

Number of Neighbors : 1  accuracy : 0.6666666666666666
Number of Neighbors : 3  accuracy : 0.5555555555555556
Number of Neighbors : 5  accuracy : 0.6111111111111112
Number of Neighbors : 7  accuracy : 0.6111111111111112
Number of Neighbors : 9  accuracy : 0.6111111111111112

/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/alok.g.v/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)